### ISSUE TITLE
repositioning the search bar erase button

### ISSUE THREAD

**Issue by adisuyash** [duc-beluga/CryptoInfo#5]
### Deescription : 
Erase button **`X`** of the search bar, needs to be shifted to the right .

### Screenshots  :
Here are some screenshots which shows the problem and required solution
#### Before
<img width="289" alt="search bar ui" src="https://github.com/duc-beluga/CryptoInfo/assets/116362593/dc32826e-8367-49f0-89ec-89736d1d7716">
<br>
<img width="289" alt="search bar ui" src="https://github.com/duc-beluga/CryptoInfo/assets/116362593/e94a0d69-2763-4a4c-8480-53e9c67328b9">

#### After
<img width="289" alt="search bar new ui" src="https://github.com/duc-beluga/CryptoInfo/assets/116362593/f225c1b0-1d78-41ee-8fa1-5e4cb463c4b8">

**Comment by contawo** [comment]
Have you sent a pull request of your code?

**Comment by adisuyash** [comment]
> Have you sent a pull request of your code?

Not yet
